In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn import svm

In [4]:
df=pd.read_excel("C:/Users/DELL/Downloads/diabetes.xlsx")

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31,0
2,8,183.0,64.0,0.0,0.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [28]:
#Checking the null values..
df.isnull().sum()

Pregnancies                 0
Glucose                     1
BloodPressure               2
SkinThickness               2
Insulin                     4
BMI                         0
DiabetesPedigreeFunction    2
Age                         0
Outcome                     0
dtype: int64

In [30]:
df = df.dropna()
df.shape

(757, 9)

In [33]:
 #checking  duplicate values

df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
763    False
764    False
765    False
766    False
767    False
Length: 757, dtype: bool

In [37]:
#delete duplicate data

df.drop_duplicates()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31,0
2,8,183.0,64.0,0.0,0.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,0.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,0.0,0.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,0.0,30.4,0.315,23,0

In [29]:
#Checking the meta data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   767 non-null    float64
 2   BloodPressure             766 non-null    float64
 3   SkinThickness             766 non-null    float64
 4   Insulin                   764 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  766 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [10]:
#Doing some basic statistic
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,767.000000,766.000000,766.000000,764.000000,768.000000,766.000000,768.000000,768.000000
mean,3.833333,120.988266,69.169713,20.550914,80.121728,32.053776,0.470943,33.282552,0.350260
std,3.350586,32.176749,19.242652,15.968495,116.407280,7.797048,0.330656,11.760301,0.477362
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,64.000000,0.000000,0.000000,27.375000,0.241500,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.500000,80.000000,32.000000,126.250000,36.525000,0.625500,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [12]:
#Checking the unique values of dependent variable
df["Outcome"].unique()

array([1, 0], dtype=int64)

In [38]:
#Check the dimensions
df.shape

(757, 9)

In [40]:
#Shortcut to scale all independent variable in one go.... 
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X =  pd.DataFrame(sc_X.fit_transform(df.drop(["Outcome"],axis = 1),),
        columns=['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'])

In [42]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.643475,0.839027,0.147227,0.905555,-0.688636,0.199177,0.470882,1.428491
1,-0.842524,-1.115929,-0.164669,0.530073,-0.688636,-0.697087,-0.361871,-0.194030
2,1.237874,1.925113,-0.268634,-1.284758,-0.688636,-1.119611,0.606657,-0.108634
3,-0.842524,-0.991805,-0.164669,0.154591,0.118127,-0.505030,-0.917040,-1.047989
4,-1.139724,0.497685,-1.516215,0.905555,0.753238,1.415536,5.482489,-0.023239

In [44]:
#Separating dataset into independent and dependent variables
X = df.iloc[:, 0:8].values
y = df.iloc[:, -1].values

In [46]:
#Splitting into training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3,random_state=0)

In [48]:
#Fitting Decisiontree into dataset
from sklearn.tree import DecisionTreeClassifier
#Creating a confusion matrix
from sklearn.metrics import confusion_matrix
#Check the accuracy
from sklearn.metrics import accuracy_score


dtree_c=DecisionTreeClassifier(criterion='entropy',random_state=0)
dtree_c.fit(X_train,y_train)
dtree_pred=dtree_c.predict(X_test)
dtree_cm=confusion_matrix(y_test,dtree_pred)
print("The accuracy of DecisionTreeClassifier is:",accuracy_score(dtree_pred,y_test))

The accuracy of DecisionTreeClassifier is: 0.6710526315789473

In [49]:
print(dtree_cm)

[[110  36]
 [ 39  43]]